### ISSUE TITLE
ChatLiteLLM?

### ISSUE THREAD

**Issue by krrishdholakia** [timedomain-tech/open-creator#6]
Hi @ChuxiJ, 

Saw you'd commented out ChatLiteLLM
https://github.com/timedomain-tech/open-creator/blob/90350e87d3b1aa6fc7c36e49d74ec45253a982f0/creator/llm/llm_creator.py#L3C1-L3C1

Anything we were missing? I'm the maintainer of litellm. 

Any feedback would be helpful

**Comment by ChuxiJ** [comment]
I found there has FunctionMessage and FunctionMessageChunk define in langchain.chat_models.litellm, and it defined in langchain.schema.messages too, currently if I use funciton call with litellm, it will be raise an error that "raise ValueError(f"Got unknown type {message}")" which the message is a FunctionMessage. So I remove the define of FunctionMessage and FunctionMessageChunk in langchain.chat_models.litellm, and import from langchain.schema.messages like below.

1. from langchain.schema.messages import (
2.     AIMessage,
3.     AIMessageChunk,
4.     BaseMessage,
5.     BaseMessageChunk,
6.     ChatMessage,
7.     ChatMessageChunk,
8.     HumanMessage,
9.     HumanMessageChunk,
10.     SystemMessage,
11.     SystemMessageChunk,
12.     FunctionMessage,
13.     FunctionMessageChunk
14. )


Exception raise in the function define:

1. def _convert_message_to_dict(message: BaseMessage) -> dict:
2.     if isinstance(message, ChatMessage):
3.         message_dict = {"role": message.role, "content": message.content}
4.     elif isinstance(message, HumanMessage):
5.         message_dict = {"role": "user", "content": message.content}
6.     elif isinstance(message, AIMessage):
7.         message_dict = {"role": "assistant", "content": message.content}
8.         if "function_call" in message.additional_kwargs:
9.             message_dict["function_call"] = message.additional_kwargs["function_call"]
10.     elif isinstance(message, SystemMessage):
11.         message_dict = {"role": "system", "content": message.content}
12.     elif isinstance(message, FunctionMessage):
13.         message_dict = {
14.             "role": "function",
15.             "content": message.content,
16.             "name": message.name,
17.         }
18.     else:
19.         raise ValueError(f"Got unknown type {message}")
20.     if "name" in message.additional_kwargs:
21.         message_dict["name"] = message.additional_kwargs["name"]
22.     return message_dict

**Comment by krrishdholakia** [comment]
That's odd. Thanks for letting me know @ChuxiJ
